#if !canImport(ObjectiveC)
import XCTest

extension AllTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AllTests = [
        ("testAll", testAll),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AllTests.__allTests__AllTests),
    ]
}
#endif
