ignore:
  - "Tests"
  
codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: up
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
