name: Pre-publish
on:
  push:
    tags:
    - 'rc/[0-9]+.[0-9]+.[0-9]+'
jobs:
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: pod lib lint
  create-release:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: jungwinter/split@v1
      id: split
      with:
        seperator: '/'  # this is correct, the action is typo’d despite warning
        msg: ${{ github.ref }}

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # zero means “all” (or push fails)

    - run: echo ${{ steps.split.outputs._3 }}

    - name: Update committed versions
      run: |
        ruby -i -pe "sub(/CURRENT_PROJECT_VERSION = [0-9.]+/, 'CURRENT_PROJECT_VERSION = $v')" PromiseKit.xcodeproj/project.pbxproj
        ruby -i -pe "sub(/s.version = '[0-9.]+'/, 's.version = \"$v\"')" PromiseKit.podspec
      env:
        v: ${{ steps.split.outputs._3 }}
    - run: |
        ! (git diff --quiet)
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "PromiseKit $v"
        git tag rc/$v/step-2
        git push origin rc/$v/step-2
        echo "SHA=$(git rev-parse --short rc/$v/step-2)" >> $GITHUB_ENV
      env:
        v: ${{ steps.split.outputs._3 }}

    - uses: softprops/action-gh-release@v1
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.split.outputs._3 }}
        name: ${{ steps.split.outputs._3 }}
        draft: true
        prerelease: true
        target_commitish: ${{ env.SHA }}
